In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn import metrics
from sklearn.model_selection import train_test_split

## Question 1

In [2]:
digit = load_digits()
x=digit.data
y=digit.target

In [3]:
x.shape , y.shape

((1797L, 64L), (1797L,))

## Question 2

In [4]:
x = preprocessing.scale(x)
x

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [5]:
df = pd.DataFrame(x)
df.head()

0         1         2         3         4         5         6         7   \
0  0.0 -0.335016 -0.043081  0.274072 -0.664478 -0.844129 -0.409724 -0.125023   
1  0.0 -0.335016 -1.094937  0.038648  0.268751 -0.138020 -0.409724 -0.125023   
2  0.0 -0.335016 -1.094937 -1.844742  0.735366  1.097673 -0.409724 -0.125023   
3  0.0 -0.335016  0.377661  0.744919  0.268751 -0.844129 -0.409724 -0.125023   
4  0.0 -0.335016 -1.094937 -2.551014 -0.197863 -1.020657 -0.409724 -0.125023   

         8         9     ...           54        55        56        57  \
0 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   
1 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   
2 -0.059078 -0.624009    ...     0.259230 -0.209785 -0.023596 -0.299081   
3 -0.059078  1.879691    ...     1.072563 -0.209785 -0.023596 -0.299081   
4 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   

         58        59        60        61        62        63  
0  0.086719  0.208293 -0.366771 -1.146647 -0.505670 -0.196008  
1 -1.089383 -0.249010  0.849632  0.548561 -0.505670 -0.196008  
2 -1.089383 -2.078218 -0.164037  1.565686  1.695137 -0.196008  
3  0.282736  0.208293  0.241430  0.379040 -0.505670 -0.196008  
4 -1.089383 -2.306869  0.849632 -0.468564 -0.505670 -0.196008  

[5 rows x 64 columns]

## Question 3

## Question 4

In [6]:
from sklearn.decomposition import PCA
pca = PCA(n_components=16)
principalComponents = pca.fit_transform(x)
principalComponents

array([[ 1.91420214, -0.95445897, -3.94602484, ..., -0.1926781 ,
         0.84272223, -0.07122862],
       [ 0.58899074,  0.9246326 ,  3.9248943 , ..., -0.40930963,
        -0.77134893,  0.21405173],
       [ 1.30205161, -0.31716368,  3.02328754, ..., -0.95832276,
        -1.14883635, -0.3968076 ],
       ...,
       [ 1.02260592, -0.14796577,  2.46985516, ...,  0.24504064,
         0.33538397, -1.20573978],
       [ 1.07600178, -0.38095277, -2.45552541, ..., -0.82390391,
        -0.05540179, -0.09872016],
       [-1.25771354, -2.22766502,  0.28347665, ...,  0.74674198,
         1.81773778, -0.28737303]])

In [7]:
#principalDf = pd.DataFrame(data = principalComponents, columns = ['principal component 1', 'principal component 2'])

In [8]:
#principalDf

In [9]:
x = principalComponents
x.shape , y.shape

((1797L, 16L), (1797L,))

In [10]:
from sklearn.linear_model import LogisticRegression
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.3)

In [11]:
reg = LogisticRegression()
reg.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [12]:
pred = reg.predict(X_test)

In [13]:
metrics.accuracy_score(Y_test,pred)*100

92.96296296296296

In [14]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        52
          1       0.82      0.82      0.82        56
          2       0.96      0.98      0.97        53
          3       0.98      0.91      0.94        56
          4       0.98      0.95      0.96        58
          5       0.95      0.96      0.95        54
          6       0.96      0.95      0.96        57
          7       0.98      1.00      0.99        54
          8       0.81      0.77      0.79        44
          9       0.84      0.93      0.88        56

avg / total       0.93      0.93      0.93       540



In [15]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test,pred))

[[52  0  0  0  0  0  0  0  0  0]
 [ 0 46  0  0  0  0  0  0  4  6]
 [ 0  0 52  0  1  0  0  0  0  0]
 [ 0  0  1 51  0  0  0  1  3  0]
 [ 0  0  0  0 55  0  0  0  0  3]
 [ 0  0  0  0  0 52  1  0  0  1]
 [ 0  2  0  0  0  1 54  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  0]
 [ 0  6  1  1  0  1  1  0 34  0]
 [ 0  2  0  0  0  1  0  0  1 52]]
